name: fromAl
favicon: null
layout_spectrum: 0.29079
typography_spectrum: 0.7955390471033752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7027724459767342
  lightness: 0.9598271055147052
  saturation: 0.8129931567236781
  rhythmicContrast: 0.4427708250004798
purpose: []
